#!/usr/bin/env bun
/**
 * Bundles core principles from .dust/principles/ into a TypeScript module.
 * This eliminates runtime file system dependencies for principle lookup.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const principlesDir = join(root, '.dust', 'principles')
const outputFile = join(root, 'lib', 'bundled-core-principles.ts')

// Read all principle files
const files = readdirSync(principlesDir)
const mdFiles = files.filter(f => f.endsWith('.md'))

// Generate the module content
let output = `/**
 * Auto-generated bundled core principles.
 * DO NOT EDIT - generated by scripts/bundle-core-principles.ts
 */

interface BundledPrinciple {
  slug: string
  content: string
}

export const BUNDLED_PRINCIPLES: BundledPrinciple[] = [
`

for (const file of mdFiles) {
  const slug = file.replace(/\.md$/, '')
  const filePath = join(principlesDir, file)
  const content = readFileSync(filePath, 'utf-8')

  // Escape backticks and backslashes in content
  const escapedContent = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${')

  output += `  {\n    slug: ${JSON.stringify(slug)},\n    content: \`${escapedContent}\`,\n  },\n`
}

output += ']\n'

// Write the generated module
writeFileSync(outputFile, output, 'utf-8')

console.log(`Bundled ${mdFiles.length} principles into ${outputFile}`)
